# Generated by Django 3.1.4 on 2021-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201223_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('User', 'Normal'), ('Vet', 'Vetenarian'), ('Shop', 'ShopOwner')], default='User', max_length=30),
        ),
    ]
