# Generated by Django 3.1.4 on 2021-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('vet', 'Vetenarian'), ('shop', 'Shop Owner')], default='normal', max_length=30),
        ),
    ]
