# Generated by Django 3.1.4 on 2021-01-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210107_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('vet', 'Vetenarian'), ('shop', 'Shop Owner')], default='null', max_length=30),
        ),
    ]
