# Generated by Django 3.1.4 on 2021-01-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('work_hours', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='default_emergency.png', upload_to='emergency_pics')),
            ],
        ),
    ]
