# Generated by Django 3.1.4 on 2021-01-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencylink',
            old_name='Phone',
            new_name='phone',
        ),
    ]
