# Generated by Django 3.1.4 on 2021-01-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vet_pics'),
        ),
    ]
