# Generated by Django 3.1.4 on 2021-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_auto_20210109_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='vet_name',
            field=models.CharField(default='Vet', max_length=30),
        ),
    ]
