# Generated by Django 3.1.4 on 2021-01-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_vet_vet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vet',
            old_name='Certification',
            new_name='certification',
        ),
    ]
