# Generated by Django 3.1.4 on 2021-01-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210116_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='food_pics'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
